### PR TITLE
Updates _lms-overrides.scss to hide course-info tags

### PR DESCRIPTION
**Pull request by profmikegreene**
@bdero @bradenmacdonald Will this file be automatically included in our Ginko upgrade?

### CODE REVIEW

**Comment by pomegranited** [comment]
@profmikegreene I'll ensure this change is included in your production upgrade.  CC @bdero @bradenmacdonald

**Comment by profmikegreene** [comment]
I believe I fixed the merge conflicts, please apply to dev @pomegranited.

Is it possible to also change ${marketing_link('COURSES')} at https://github.com/edx/edx-platform/blob/803db4ee3ff0bdbc388d52d5285d24a3b1b4b588/lms/templates/navigation/navbar-authenticated.html#L16 and https://github.com/edx/edx-platform/blob/803db4ee3ff0bdbc388d52d5285d24a3b1b4b588/lms/templates/navigation/navbar-not-authenticated.html#L20 to https://online.duke.edu/course-listing/? We are changing our marketing strategy to use that online.duke site everywhere.

**Comment by pomegranited** [comment]
So sorry for dropping the ball on this before your Ginkgo upgrade, @profmikegreene !  I've tested this change and it works fine; will merge it now and deploy to stage for you to verify.

**Comment by pomegranited** [comment]
@profmikegreene  To use the `marketing_link` feature, we need to provide a [different base URL for all your marketing links](https://github.com/edx/edx-platform/wiki/Alternate-site-for-marketing-links#to-run-with-an-alternate-marketing-site), including the home page.  This feature is used by edX to ensure that unauthenticated users who visit [courses.edx.org](https://courses.edx.org) (their LMS) are redirected to [www.edx.org](https://www.edx.org) (their marketing site).  Authenticated users are redirected to [courses.edx.org/dashboard](https://courses.edx.org/dashboard) as usual.

Unfortunately, it doesn't allow you to pick and choose just a few links to redirect; you have to provide something for them all.  But we can use fully-qualified URLs for the pages that exist on your LMS.

These settings can be changed by users with "superuser" access from the Django Admin interface, under Site Configuration, which includes you and Liz.

These settings should be adjusted with care, and should always be tested on stage before use in production.  See **Caveats** below for some things to be aware of.

For example, if you add these settings to your [stage.extend.duke.edu](https://stage.extend.duke.edu) service's [Site Configuration](https://stage.extend.duke.edu/admin/site_configuration/siteconfiguration/):

```javascript
{
  "ENABLE_MKTG_SITE":true,
  "MKTG_URLS":{
    "ROOT":"https://online.duke.edu",
    "COURSES":"/course-listing/",
    "ABOUT":"/our-work/",
    "SCHOOLS":"/faculty/",
    "NEWS":"/news/",
    "CONTACT":"/faq/",
    "FAQ":"/faq/",
    "HOW_IT_WORKS":"/faq/",
    "WHAT_IS_VERIFIED_CERT":"/faq/",
    "TOS_AND_HONOR":"https://stage.extend.duke.edu/tos",
    "TOS":"https://stage.extend.duke.edu/tos",
    "HONOR":"https://stage.extend.duke.edu/tos",
    "PRIVACY":"https://stage.extend.duke.edu/tos"
  }
}
```

It will cause the following behaviours:
* Unauthenticated users who visit [extend.duke.edu](https://extend.duke.edu) are redirected to [online.duke.edu](https://online.duke.edu), and so a login/register pathway back to the LMS should be added to that site.
* Authenticated users who visit [extend.duke.edu](https://extend.duke.edu) are redirected to [extend.duke.edu/dashboard](https://extend.duke.edu/dashboard), as usual.
* "Courses" links will be rendered as [online.duke.edu/course-listing](https://online.duke.edu/course-listing)
* "About" links will be rendered as [online.duke.edu/our-work/](https://online.duke.edu/our-work/)
* "News" links will be rendered as [online.duke.edu/news/](https://online.duke.edu/news/)
* "Schools" links will be rendered as [online.duke.edu/faculty/](https://online.duke.edu/faculty/)
* "Contact", "FAQ", "How it Works", and "What is a verified certificate?"  links will be rendered as [online.duke.edu/faq/](https://online.duke.edu/faq/)
* And your "Terms of Service", "Honor Code", and "Privacy" links would be rendered as [stage.extend.duke.edu/tos](https://stage.extend.duke.edu/tos).

**Caveats**:
* Changes to Site Configuration take 3 minutes to take effect on your site.
* Unfortunately, it doesn't work to use `"ROOT": "https://stage.extend.duke.edu"`, and instead provide the fully-qualified URLs for `"COURSES": "https://online.duke.edu/course-listing/"` and `"FAQ": "https://online.duke.edu/faq/"` etc.  This causes an infinite redirect on the `stage.extend.duke.edu` home page.  Fixing this bug would require an upstream code change.
* Your [theme footer](https://github.com/DukeLearningInnovation/duke-extend-theme/blob/master/lms/templates/footer.html#L22-L30) also hard-codes the links to your "About" and "Contact Us" pages, so these marketing link changes will not change them unless we change your theme.
* Some marketing links, e.g. "Privacy" and "News" (aka ["Legal" links](https://github.com/DukeLearningInnovation/edx-platform/blob/duke-ginkgo.1/lms/templates/footer.html#L105-L112)) are not used on your site, because your theme [overrides the footer template](https://github.com/DukeLearningInnovation/duke-extend-theme/blob/master/lms/templates/footer.html#L20-L33) where they usually appear.
* Setting `"ENABLE_MKTG_SITE":true` alters the header links displayed to unauthenticated users to include the ["How it Works", "Courses", and "Schools" links](https://github.com/DukeLearningInnovation/edx-platform/blob/duke-ginkgo.1/lms/templates/navigation/navbar-not-authenticated.html#L13-L27).
  However since your /login and /register pages will still redirect to OneLink, no one will see these pages, so it's not an issue here.
* More information available here: https://github.com/edx/edx-platform/wiki/Alternate-site-for-marketing-links#to-run-with-an-alternate-marketing-site

**Pull request merged**
